#!/usr/bin/env node
// Builds the single-file panel and the release zip:
//   dist/IDtoAE.jsx            everything in one file (panel, AE code, InDesign engine)
//   dist/IDtoAE-v<version>.zip IDtoAE.jsx + "How to install.txt"
//
// Usage: node build.js

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

// ExtendScript reads scripts most reliably as ASCII, so escape everything else.
const ascii = (s) => s.replace(/[^\x00-\x7e]/g, (c) => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));
const asciiComments = (s) => s.replace(/[^\x00-\x7e]/g, (c) => ({ '—': '-', '·': '.', '→': '->' }[c] || '?'));

const version = (read('IDtoAE/IDtoAE_AE.jsx').match(/NS\.VERSION = "([^"]+)"/) || [])[1];
if (!version) throw new Error('Could not find NS.VERSION in IDtoAE/IDtoAE_AE.jsx');

let panel = read('IDtoAE.jsx');
panel = panel.replace(/^#include "([^"]+)"\s*$/gm, (_, file) => {
  const src = read(file);
  return `// ---- ${file} ----\n${src}\n// ---- end ${file} ----`;
});

// The InDesign engine travels inside the panel as a string.
const engine = read('IDtoAE/IDtoAE_InDesign.jsx');
const engineLiteral = '"' + engine
  .replace(/\\/g, '\\\\')
  .replace(/"/g, '\\"')
  .replace(/\r?\n/g, '\\n') + '"';
const header = `/*
 * IDtoAE v${version} - InDesign to After Effects
 * by Andrew Dean - https://andrewjdean.com
 * Copyright (c) 2026 Andrew Dean. MIT License - see LICENSE in the repository.
 *
 * Install: put this file in your After Effects "Scripts/ScriptUI Panels" folder,
 * restart After Effects, then open Window > IDtoAE.jsx.
 * Generated by build.js - edit the source files in the repository instead.
 */
`;
const bundle = header + '\nvar IDtoAE = IDtoAE || {};\nIDtoAE.ENGINE_SOURCE = ' + ascii(engineLiteral) + ';\n\n' + panel;

const out = ascii(asciiCommentsOutsideStrings(bundle));
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist/IDtoAE.jsx'), out);

// Non-ASCII only appears in comments and string literals; comments get plain
// replacements, strings keep their characters through \u escapes (ascii()).
function asciiCommentsOutsideStrings(s) {
  return s.replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*/g, (c) => asciiComments(c));
}

const guide = `IDtoAE v${version} - InDesign to After Effects
by Andrew Dean - https://andrewjdean.com

INSTALL (Mac)
1. Quit After Effects.
2. In Finder choose Go > Go to Folder... and paste:
     ~/Library/Preferences/Adobe/After Effects/
   Open the folder with the highest version number (for example 26.3),
   then Scripts > ScriptUI Panels. Create the "Scripts" and "ScriptUI Panels"
   folders if they are missing.
3. Drag IDtoAE.jsx into ScriptUI Panels.
4. Open After Effects. Go to Settings > Scripting & Expressions and turn on
   "Allow Scripts to Write Files and Access Network".
5. Open Window > IDtoAE.jsx and dock the panel.

INSTALL (Windows, untested)
Same steps, with the folder:
     %APPDATA%\\Adobe\\After Effects\\<version>\\Scripts\\ScriptUI Panels

USE
- Choose... picks the .indd file, then Build comps. InDesign must be installed;
  the first time, macOS may ask to let After Effects control InDesign: click OK.
- Swatch comp only builds a comp of the document's swatches in sRGB.
- Break apart selected layers splits shape layers into one layer per shape.

UPDATE
Replace IDtoAE.jsx with the new version and restart After Effects.
`;
fs.writeFileSync(path.join(root, 'dist/How to install.txt'), guide);

const zip = `IDtoAE-v${version}.zip`;
fs.rmSync(path.join(root, 'dist', zip), { force: true });
for (const old of fs.readdirSync(path.join(root, 'dist'))) {
  if (/^IDtoAE-v.*\.zip$/.test(old)) fs.rmSync(path.join(root, 'dist', old));
}
execFileSync('zip', ['-q', '-X', zip, 'IDtoAE.jsx', 'How to install.txt'], { cwd: path.join(root, 'dist') });

console.log(`Built dist/IDtoAE.jsx (${(out.length / 1024).toFixed(0)} KB) and dist/${zip}`);
